# Generated by Django 2.2.4 on 2019-08-14 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('card', models.ImageField(db_column='Картинка', upload_to='ugadaika/card/')),
                ('card_name', models.CharField(db_column='Название картинки', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CardShirts',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('shirt_name', models.CharField(db_column='Имя рубашки', max_length=50)),
                ('shirt_picture', models.ImageField(db_column='Картинка рубашки', upload_to='ugadaika/shirt/')),
            ],
        ),
        migrations.CreateModel(
            name='SoundPlace',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('place_name', models.CharField(db_column='Положение звука', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sounds',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('sound_name', models.CharField(db_column='Название звука', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CardsSoundsPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ugadaika.Cards')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ugadaika.SoundPlace')),
                ('sound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ugadaika.Sounds')),
            ],
        ),
        migrations.AddField(
            model_name='cards',
            name='sound',
            field=models.ManyToManyField(through='ugadaika.CardsSoundsPlace', to='ugadaika.Sounds'),
        ),
    ]
