# Generated by Django 2.2.4 on 2019-08-14 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugadaika', '0002_remove_cardssoundsplace_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cards',
            name='sound',
        ),
    ]
