# Generated by Django 2.2.4 on 2019-08-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugadaika', '0004_auto_20190814_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cards',
            name='sound'

        ),
        migrations.AddField(
            model_name='cards',
            name='sound',
            field=models.ManyToManyField(to='ugadaika.Sounds'),
        ),
    ]
