# Generated by Django 2.2.4 on 2019-08-14 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ugadaika', '0005_auto_20190814_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardssoundsplace',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ugadaika.SoundPlace'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='cards',
            name='sound'
        ),
        migrations.AddField(
            model_name='cards',
            name='sound',
            field=models.ManyToManyField(through='ugadaika.CardsSoundsPlace', to='ugadaika.Sounds'),
        ),
    ]
