# Generated by Django 2.2.4 on 2019-08-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugadaika', '0007_auto_20190814_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndingFeature',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('ending_name', models.CharField(db_column='Окончание', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialFeature',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('material_name', models.CharField(db_column='Материал', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SexFeature',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('sex_name', models.CharField(db_column='Род', max_length=200)),
            ],
        ),
    ]
